version: 2
jobs:
  build:
    docker:
      - image: docker:17.07.0-ce-git

    # python:
    #   version: 2.7.12
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip
            pip install \
              docker-compose==1.16.1 \
              awscli==1.11.170
      - run: docker-compose build
      - run: docker run -it rocket-snake /bin/sh -c "npm test"
