# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: node:8-alpine

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm test

      # deploy
      - setup_remote_docker

      - run:
          name: Deploying docker image
          command: |
            apk update
            apk add py-pip
            pip install awscli
            aws configure set region eu-central-1
            aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
            aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
            login="$(aws ecr get-login --no-include-email)"
            apk add docker
            pip install docker-compose
            ${login}
            docker-compose build
            ECR_ENDPOINT="660113754429.dkr.ecr.eu-central-1.amazonaws.com/rocket-snake"
            docker tag rocket-snake "${ECR_ENDPOINT}:${CIRCLE_SHA1}"
            docker push "${ECR_ENDPOINT}:${CIRCLE_SHA1}"


# if [[ "${CIRCLE_BRANCH}" == "master" || "$(CIRCLE_BRANCH)" == "artem/circle" ]]; then
# fi
